name: FTP Connection Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Create FTP Test File
        run: |
          echo "TAV PETROIL FTP TEST 123" > ftp-test.txt
          echo "Created test file:"
          cat ftp-test.txt

      - name: Upload FTP Test
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /
          dangerous-clean-slate: false
          exclude: |
            **/*
            !ftp-test.txt
